apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogcat
  labels:
    app: dogcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dogcat
  template:
    metadata:
      labels:
        app: dogcat
    spec:
      containers:
      - name: dogcat
        image: dogcat
        ports:
        - containerPort: 4000
