{{- $region := .Values.region | required ".Values.region is required." -}}
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  name: {{ include "dogcat.fullname" . }}
  labels:
    {{- include "dogcat.labels" . | nindent 4 }}
spec:
  deletionPolicy: {{ .Values.cloudsql.deletionPolicy }}
  forProvider:
    databaseVersion: {{ .Values.cloudsql.databaseVersion }}
    region: {{ $region }}
    settings:
    - tier: {{ .Values.cloudsql.tier }}
      availabilityType: {{ .Values.cloudsql.availabilityType }}
      diskSize: 10
  writeConnectionSecretToRef:
    name: {{ include "dogcat.fullname" . }}-cloudsql-conn
    namespace: {{ .Release.Namespace }}
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: Database
metadata:
  name: {{ include "dogcat.fullname" . }}
  labels:
    {{- include "dogcat.labels" . | nindent 4 }}
spec:
  deletionPolicy: {{ .Values.cloudsql.deletionPolicy }}
  forProvider:
    charset: 'UTF8'
    collation: 'en_US.UTF8'
    instanceRef:
      name: {{ include "dogcat.fullname" . }}
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: User
  name: {{ include "dogcat.fullname" . }}
  labels:
    {{- include "dogcat.labels" . | nindent 4 }}
spec:
  forProvider:
    instanceRef:
      name: {{ include "dogcat.fullname" . }}
    passwordSecretRef:
      name: {{ include "dogcat.fullname" . }}
      key: password
