{{- $project := .Values.project | required ".Values.project is required." -}}
{{- $region := .Values.region | required ".Values.region is required." -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dogcat.fullname" . }}
  labels:
    {{- include "dogcat.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dogcat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dogcat.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dogcat.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_CONN
              valueFrom:
                secretKeyRef:
                  name: {{ include "dogcat.fullname" . }}-cloudsql-conn
                  key: connectionName
                  optional: false
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dogcat.fullname" . }}
                  key: password
                  optional: false
          args:
            - server
            - --driver
            - postgres
            - --conn-str
            - host=$(DB_CONN) user={{ include "dogcat.fullname" . }} dbname={{ include "dogcat.fullname" . }} password=$(DB_PASSWORD) sslmode=disable
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
