{{- $project := .Values.project | required ".Values.project is required." -}}
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: {{ include "dogcat.fullname" . }}
spec:
  forProvider:
    displayName: Used by dogcat application for database access
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: {{ include "dogcat.fullname" . }}-cloudsql
spec:
  forProvider:
    project: {{ $project }}
    role: roles/cloudsql.client
    member: serviceAccount:{{ include "dogcat.fullname" . }}@{{ $project }}.iam.gserviceaccount.com
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  name: {{ include "dogcat.fullname" . }}
spec:
  forProvider:
    serviceAccountIdRef:
      name: {{ include "dogcat.fullname" . }}
    role: roles/iam.workloadIdentityUser
    member: serviceAccount:{{ $project }}.svc.id.goog[{{ .Release.Namespace }}/{{ include "dogcat.fullname" . }}]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dogcat.fullname" . }}
  labels:
    {{- include "dogcat.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ include "dogcat.fullname" . }}@{{ $project }}.iam.gserviceaccount.com
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
