{{- $project := .Values.project | required ".Values.project is required." -}}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ include "dogcat.fullname" . }}
spec:
  displayName: Used by dogcat application for database access
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ include "dogcat.fullname" . }}-cloudsql
spec:
  memberFrom:
    serviceAccountRef:
      name: {{ include "dogcat.fullname" . }}
  role: roles/cloudsql.client
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/{{ $project }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: {{ include "dogcat.fullname" . }}-wi
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: {{ include "dogcat.fullname" . }}
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:{{ $project }}.svc.id.goog[{{ .Release.Namespace }}/{{ include "dogcat.fullname" . }}]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dogcat.fullname" . }}
  labels:
    {{- include "dogcat.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ include "dogcat.fullname" . }}@{{ $project }}.iam.gserviceaccount.com
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
