options:
  logging: CLOUD_LOGGING_ONLY
steps:
- id: 'target environment'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "***********************"
      echo "$_TARGET_ENV"
      echo "***********************"
