// Code generated by ent, DO NOT EDIT.

package db

import (
	"time"

	"github.com/NucleusEngineering/dogcat/chapter02b/ent/db/score"
	"github.com/NucleusEngineering/dogcat/chapter02b/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	scoreFields := schema.Score{}.Fields()
	_ = scoreFields
	// scoreDescCreatedAt is the schema descriptor for created_at field.
	scoreDescCreatedAt := scoreFields[0].Descriptor()
	// score.DefaultCreatedAt holds the default value on creation for the created_at field.
	score.DefaultCreatedAt = scoreDescCreatedAt.Default.(func() time.Time)
}
